[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/dgm/*"
  to = "https://dgm1.s3.eu-de.cloud-object-storage.appdomain.cloud"
  status = 200
  force = true
  # Erzwingt, dass keine automatische Text-Umwandlung stattfindet
  headers = {X-From = "Netlify"} 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
